# This configuration file tells Dependabot how to check for dependency updates
# Documentation: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
registries:
  tfc-private:
    type: terraform-registry
    url: https://app.terraform.io
    # Create a Dependabot secret named TF_API_TOKEN with a valid HCP Terraform user/team token
    token: '${{secrets.TF_API_TOKEN}}'
updates:
  # Scan each module subdirectory
  - package-ecosystem: 'terraform'
    directory: '/modules/app-service-function'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # Trigger: touch config to enqueue Dependabot re-run (2025-08-26)

  - package-ecosystem: 'terraform'
    directory: '/modules/app-service-web'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  - package-ecosystem: 'terraform'
    directory: '/modules/monitoring'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  - package-ecosystem: 'terraform'
    directory: '/modules/networking'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  - package-ecosystem: 'terraform'
    directory: '/modules/storage-account'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'
