# This configuration file tells Dependabot how to check for dependency updates
# Documentation: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
registries:
  tfc-private:
    type: terraform-registry
    url: https://app.terraform.io
    # Create a Dependabot secret named TF_API_TOKEN with a valid HCP Terraform user/team token
    token: '${{secrets.TF_API_TOKEN}}'
updates:
  # Scan each module subdirectory

  # app-service-plan-function
  - package-ecosystem: 'terraform'
    directory: '/modules/app-service-plan-function'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # app-service-plan-web
  - package-ecosystem: 'terraform'
    directory: '/modules/app-service-plan-web'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # function-app
  - package-ecosystem: 'terraform'
    directory: '/modules/function-app'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # monitoring
  - package-ecosystem: 'terraform'
    directory: '/modules/monitoring'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # networking
  - package-ecosystem: 'terraform'
    directory: '/modules/networking'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # private-endpoint
  - package-ecosystem: 'terraform'
    directory: '/modules/private-endpoint'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # storage-account
  - package-ecosystem: 'terraform'
    directory: '/modules/storage-account'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'

  # service-bus
  - package-ecosystem: 'terraform'
    directory: '/modules/service-bus'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'


  # application-insights
  - package-ecosystem: 'terraform'
    directory: '/modules/application-insights'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'


    # Container Instance
  - package-ecosystem: 'terraform'
    directory: '/modules/container-instances'
    registries:
      - tfc-private
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'terraform'
    assignees:
      - 'stuartshay'
