directory:
  - modules

skip-path:
  - modules/app-service-web/examples/
  - modules/monitoring/examples/

framework:
  - terraform

skip-check:
  - CKV_AZURE_1 # Ensure that 'Secure transfer required' is set to 'Enabled'
  - CKV2_AZURE_1 # Ensure storage for critical data are encrypted with Customer Managed Key
  - CKV2_AZURE_8 # Ensure the storage account containing the container with activity logs is encrypted with BYOK (Use Your Own Key)
  - CKV_AZURE_225 # Ensure the App Service Plan is zone redundant
  - CKV_AZURE_212 # Ensure App Service has a minimum number of instances for failover
  - CKV_AZURE_211 # Ensure App Service plan suitable for production use
  - CKV_AZURE_244 # Avoid the use of local users for Azure Storage unless necessary
  - CKV_AZURE_213 # Ensure that App Service configures health check
  - CKV_AZURE_16 # Ensure that Register with Azure Active Directory is enabled on App Service
  - CKV_AZURE_13 # Ensure App Service Authentication is set on Azure App Service
  - CKV_AZURE_88 # Ensure that app services use Azure Files
  - CKV_AZURE_65 # Ensure that App service enables detailed error messages
  - CKV_AZURE_71 # Ensure that Managed identity provider is enabled for app services
  - CKV_AZURE_17 # Ensure the web app has 'Client Certificates (Incoming client certificates)' set
  - CKV_AZURE_66 # Ensure that App service enables failed request tracing
  - CKV_AZURE_222 # Ensure that Azure Web App public network access is disabled
  - CKV_AZURE_63 # Ensure that App service enables HTTP logging
  - CKV2_AZURE_31 # Ensure VNET subnet is configured with a Network Security Group (NSG)
  - CKV2_AZURE_38 # Ensure soft-delete is enabled on Azure storage account
  - CKV2_AZURE_33 # Ensure storage account is configured with private endpoint
  - CKV2_AZURE_20 # Ensure Storage logging is enabled for Table service for read requests
  - CKV2_AZURE_21 # Ensure Storage logging is enabled for Blob service for read requests
  - CKV_AZURE_33 # Ensure Storage logging is enabled for Queue service for read, write and delete requests
  - CKV_AZURE_35 # Ensure default network access rule for Storage Accounts is set to deny
  - CKV_AZURE_36 # Ensure 'Trusted Microsoft Services' is enabled for Storage Account access
  - CKV2_AZURE_40 # Ensure storage account is not configured with Shared Key authorization
  - CKV_AZURE_59 # Ensure that Storage accounts disallow public access
  - CKV_AZURE_206 # Ensure that Storage Accounts use replication
  - CKV2_AZURE_41 # Ensure storage account is configured with SAS expiration policy

output: cli
quiet: false
compact: true
download-external-modules: false
external-checks-dir: []
# baseline: .checkov.baseline
soft-fail: false
skip-download: true
