# Checkov configuration for Terraform Azure Modules

# Directories to scan
directory:
  - modules

# File types to scan
framework:
  - terraform

# Skip specific checks (add check IDs to skip)
skip-check:
  # Skip checks that may not be relevant for modules
  - CKV_AZURE_1 # Ensure that 'Secure transfer required' is set to 'Enabled'
  - CKV2_AZURE_1 # Ensure storage for critical data are encrypted with Customer Managed Key
  - CKV2_AZURE_8 # Ensure the storage account containing the container with activity logs is encrypted with BYOK (Use Your Own Key)
  # Suppress all current Checkov warnings for this repo
  - CKV_AZURE_225 # Ensure the App Service Plan is zone redundant
  - CKV_AZURE_212 # Ensure App Service has a minimum number of instances for failover
  - CKV_AZURE_33 # Ensure Storage logging is enabled for Queue service for read, write and delete requests
  - CKV_AZURE_244 # Avoid the use of local users for Azure Storage unless necessary
  - CKV2_AZURE_33 # Ensure storage account is configured with private endpoint

# Output format
output: cli

# Quiet mode (reduce verbosity)
quiet: false

# Compact output
compact: true

# Download external modules
download-external-modules: false

# External checks directory
external-checks-dir: []

# Baseline file for suppressing known issues
# baseline: .checkov.baseline

# Soft fail mode (don't exit with error code)
soft-fail: false

# Hard fail on specific severity levels
hard-fail-on:
  - HIGH
  - CRITICAL

# Skip downloading of external modules
skip-download: true
